# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('hash_pw', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_line', models.TextField(max_length=1000)),
                ('profile_picture', models.CharField(default='paper.jpeg', max_length=255)),
                ('open_balance', models.IntegerField(default=100)),
                ('wager_balance', models.IntegerField(default=0)),
                ('spent', models.IntegerField(default=0)),
            ],
        ),
    ]
