# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170419_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/None/no-img.jpg', null=True, upload_to='apps/react/static/react/images/'),
        ),
    ]
