# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170420_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='paper.jpeg', max_length=255),
        ),
    ]
