# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react', '0003_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
