# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react', '0005_auto_20170420_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wager',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
