# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react', '0008_auto_20170420_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='win',
            field=models.BooleanField(default=None),
        ),
    ]
